# Generated by Django 3.0.4 on 2020-03-29 02:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='hotelStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffID', models.FloatField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('contactEmail', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('contactPhoneNumber', models.FloatField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
            ],
            options={
                'ordering': ('staffID',),
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomType', models.CharField(max_length=250)),
                ('hotel', models.CharField(max_length=250)),
                ('roomID', models.FloatField(blank=True, default=None, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
            ],
            options={
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.FloatField(blank=True, default=None, null=True)),
                ('userPassword', models.FloatField(blank=True, default=None, null=True)),
                ('name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('expectedMinPrice', models.IntegerField(blank=True, default=None, null=True)),
                ('expectedMaxPrice', models.IntegerField(blank=True, default=None, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(0, 'checked out'), (1, 'checked in'), (2, 'has a reservation')], default='draft', max_length=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('expectedMinPrice',),
            },
        ),
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservationID', models.FloatField(blank=True, default=None, null=True)),
                ('roomNumber', models.IntegerField(blank=True, default=None, null=True)),
                ('hotelName', models.CharField(max_length=250)),
                ('checkIn', models.DateTimeField(default=None)),
                ('checkOut', models.DateTimeField(default=None)),
                ('reserveTime', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('status', models.CharField(choices=[(0, 'UnProcessed'), (1, 'processing'), (2, 'processed')], default=None, max_length=10)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='bookinghub.User')),
            ],
            options={
                'ordering': ('reserveTime',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('rating', models.IntegerField(blank=True, default=None, null=True)),
                ('price', models.IntegerField(blank=True, default=None, null=True)),
                ('contactEmail', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('contactPhoneNumber', models.FloatField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('hotelStaff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotelStaff', to='bookinghub.User')),
            ],
            options={
                'ordering': ('rating',),
            },
        ),
    ]
