# Generated by Django 3.0.4 on 2020-03-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinghub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('0', 'Occupied'), ('1', 'Available'), ('2', 'Unavailable')], default='2', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('0', 'UnProcessed'), ('1', 'processing'), ('2', 'processed')], default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('0', 'checked out'), ('1', 'checked in'), ('2', 'has a reservation'), ('3', 'no reservation')], default='3', max_length=10),
        ),
    ]
