# Generated by Django 3.0.4 on 2020-03-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookinghub', '0003_auto_20200329_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation',
            new_name='room',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
